---
Style/AsciiComments:
    Enabled: false
Style/FileName:
    Enabled: false
Style/Lambda:
    Enabled: false
Style/HashSyntax:
    EnforcedStyle: hash_rockets
Metrics/MethodLength:
    Max: 30
Metrics/ClassLength:
    Max: 200
