daniel(1)
=========

Name
----
daniel - easy-to-use password generator

Synopsis
--------
[verse]
'daniel' [-r] [-p] [-v <version>] [-f <flags>] [-l <length>] [-P <format>]
'daniel' [-r] [-p] [-v <version>] [-P <format>] -m
'daniel' [-r] [-f <flags>] [-l <length>] -e
'daniel' [-r] [-p] [-P <format>] <reminder>...
'daniel' [-r] -a <reminder>...

Description
-----------
daniel produces passwords based on a master password, a set of parameters
(password version, length, and flags), and a code which identifies the
particular password.  As part of the password generation process, a short
reminder is produces that encodes the parameters and code; with this reminder
and the master password, the generated password can be reproduced.


'daniel' [-r] [-p] [-v <version>] [-f <flags>] [-l <length>] [-P <format>]::
	Generate one or more passwords and their corresponding reminders.
+
The user is prompted for the master password on startup, and can change it using
the `!password` command at any code prompt.  After the password is entered,
daniel produces a 6-character checksum to reassure the user that the password is
correct.
+
After this, daniel prompts for a code that indicates the purpose of the
password.  For web site passwords, this is traditionally a shortened form of the
domain name (e.g. _github.com_ for GitHub), although any UTF-8 input is
acceptable.  Once the code is entered, a password is generated and output either
to standard output or, with `-p`, to the clipboard.  This is followed by a
reminder that can be used to recreate the password only with the correct master
password.
+
If the provided code starts with an exclamation point, it is taken as a bang
command. `!!` repeats the last non-command code.

'daniel' [-r] [-p] [-v <version>] [-P <format>] -m|--existing::
	Similar to the first form, but after the code prompt, the user is prompted to
	enter an existing password.  This password is encoded into the reminder, which
	is then output.  As with the first form, the reminder is useless without the
	correct master password.
+
This form is useful to encode existing credentials.

'daniel' [-r] [-f <flags>] [-l <length>] -e|--entropy::
  Instead of generating a password, output statistics about the entropy of a
	password generated with those parameters.

'daniel' [-r] [-p] [-P <format>] <reminder>...::
  Use the specified reminders to regenerate and output their corresponding
	passwords.
+
After the user enters their master password, each password is output without
pausing.

'daniel' [-r] -a <reminder>...::
	Parse the given reminders and display the parameters and code encoded in them.

Flag Values
~~~~~~~~~~~
Flags values are specified using the `-f` option.  The flags value can be
specified in decimal, octal, or hexadecimal (using standard C notation), or by
using a string indicating the permitted symbols.  Numerical interpretations have
priority.  The bits have the following meaning:

|===
|Flag |Meaning
|1    |Exclude all digits
|2    |Exclude spaces
|4    |Exclude those punctuation marks above the digits on a US keyboard
|8    |Exclude other symbols
|16   |Exclude letters
|128  |Permit arbitrary byte sequences
|===

Alternately, the string can be composed of the following:

|===
|Character                  |Meaning
|`0`                        |Include digits
|`A` or `a`                 |Include letters
|`s` or the space character |Include spaces
|`!`												|Include punctuation marks above the digits on a US
keyboard
|`:`, `+`, or `-`           |Include other symbols
|===

The `-m` option is represented using a flags value of exactly 32 (0x20).

Commands
~~~~~~~~
Any string starting with an exclamation point that is entered at the code prompt
is considered a command.

|===
|Command              | Meaning
|`!!`                 | Repeat the previous code entry
|`!passphrase`        | Enter a new master password
|+!flags=_<value>_+   | Set a new flags value
|+!version=_<value>_+ | Change the password version
|+!length=_<value>_+  | Change the password length
|===

The `!!` command can be useful with the `-p` option if something else has been
copied to the clipboard in the mean time.

Machine-Readable Format
~~~~~~~~~~~~~~~~~~~~~~~
In the machine-readable format, each non-empty line output starts with a colon,
a message, a space, and one or more space-separated URI-encoded values.
Messages ending with question marks are prompts for information; those with
exclamation marks, an error; and the unmarked, a statement.

The prompts are as follows:
|===
|Prompt              | Response
|`:code?`            | Enter the code
|`:existing?`        | Enter an existing password
|`:master-password?` | Enter the master password
|===

The statements are as follows:
|===
| Statement          | Meaning
|`:bits-per-char`    | The number of bits of entropy per character
|`:bits-total`       | Total number of bits of entropy
|`:checksum`         | The checksum
|`:code`             | The code from a reminder
|`:flags`            | The flags in decimal and described in text
|`:length`           | The password length
|`:mask`             | The mask used to encode an existing password
|`:password-version` | The reminder's password version
|`:possible-char`    | The number of possible characters
|`:reminder`         | The reminder
|`:version`          | The password algorithm version (always 0)
|===

The errors are as follows:
|===
|Error               | Meaning
|`:invalid-command!` | The command that was entered was invalid.
|===

Options
-------
-f <flags>::
--password-flags <flags>::
	Specify the set of characters permitted in the password.  A flags value of 0
	permits all printable ASCII characters (ASCII 32–ASCII 126).  The default, 2,
	is to exclude spaces, as these are handled poorly by
	many sites.  Changing the flags value results in a completely different
	password.  To change the password at the code prompt, use `!flags=<flags>`.
+
Since daniel employs a cryptographically-secure PRNG to generate bytes and
selects the first bytes that match, a generated password might not contain a
particular type of character needed as part of a site's security policy.  In
this case, simply increase the version number until a suitable password is
chosen.

-l <length>::
--password-length <length>::
	Specify the length of the password to be generated in characters.  The default
	is 16.  If two passwords are generated with identical parameters except for
	their length, one will start with the other.  That is, changing only the
	length does not produce a completely different password.  To change the length
	at the code prompt, use `!length=<length>`.

-P <format>::
	Produce output in an alternate format.  Besides the default format, _plain_,
	_bubblebabble_ is also accepted (for BubbleBabble format).

-p::
--clipboard::
	If the clipboard gem is installed, copy the passwords to the clipboard instead
	of printing them to standard output.

-r::
--machine-readable::
	Produce machine-readable output.

-v <version>::
--password-version <version>::
	Specify a particular password version.  The default is 0.  This can be useful
	for institutions or websites that require frequently changing passwords.
	Changing the version number produces a completely different password unrelated
	to any others.  To change the password version at the code prompt, use
	`!version=<version>`.

--anonymous::
--no-anonymous::
  Specify that the reminder should be anonymous (or not).  Only version 1 can be
  anonymous, and anonymous reminders set a checksum of all zeros so as to
  minimize any information leakage.

Configuration
-------------

daniel accepts some configuration options in
`$XDG_CONFIG_HOME/daniel/main.yaml`.  This YAML file currently supports one key:
`presets`.  The corresponding value is a hash, where the keys are named presets
of values, and the value is a hash containing one or more of the following keys.

|===
|Key               | Value
|`flags`           | Flags value (integer)
|`format-version`  | Format version (0 or 1)
|`length`          | Length of the password
|`iterations`      | PBKDF2 iterations
|`salt`            | PBKDF2 salt
|`version`         | Default password version number
|===

By default, the `default` presets are used unless overridden on the command
line.  The `-t` flag can be used to default to a different preset.
